// Generated by gencpp from file hebiros/AddModelFromURDFSrvRequest.msg
// DO NOT EDIT!


#ifndef HEBIROS_MESSAGE_ADDMODELFROMURDFSRVREQUEST_H
#define HEBIROS_MESSAGE_ADDMODELFROMURDFSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hebiros
{
template <class ContainerAllocator>
struct AddModelFromURDFSrvRequest_
{
  typedef AddModelFromURDFSrvRequest_<ContainerAllocator> Type;

  AddModelFromURDFSrvRequest_()
    : model_name()
    , description_param()  {
    }
  AddModelFromURDFSrvRequest_(const ContainerAllocator& _alloc)
    : model_name(_alloc)
    , description_param(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _model_name_type;
  _model_name_type model_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_param_type;
  _description_param_type description_param;





  typedef boost::shared_ptr< ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddModelFromURDFSrvRequest_

typedef ::hebiros::AddModelFromURDFSrvRequest_<std::allocator<void> > AddModelFromURDFSrvRequest;

typedef boost::shared_ptr< ::hebiros::AddModelFromURDFSrvRequest > AddModelFromURDFSrvRequestPtr;
typedef boost::shared_ptr< ::hebiros::AddModelFromURDFSrvRequest const> AddModelFromURDFSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hebiros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'hebiros': ['/home/robot/catkin_ws/src/hebiros/hebiros/msg', '/home/robot/catkin_ws/devel/share/hebiros/msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7503667ca5355c5a12e4de26d45dcf94";
  }

  static const char* value(const ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7503667ca5355c5aULL;
  static const uint64_t static_value2 = 0x12e4de26d45dcf94ULL;
};

template<class ContainerAllocator>
struct DataType< ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hebiros/AddModelFromURDFSrvRequest";
  }

  static const char* value(const ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string model_name\n"
"\n"
"string description_param\n"
;
  }

  static const char* value(const ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.model_name);
      stream.next(m.description_param);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddModelFromURDFSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hebiros::AddModelFromURDFSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "model_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.model_name);
    s << indent << "description_param: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description_param);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEBIROS_MESSAGE_ADDMODELFROMURDFSRVREQUEST_H
