// Generated by gencpp from file hebiros/AddModelFromURDFSrv.msg
// DO NOT EDIT!


#ifndef HEBIROS_MESSAGE_ADDMODELFROMURDFSRV_H
#define HEBIROS_MESSAGE_ADDMODELFROMURDFSRV_H

#include <ros/service_traits.h>


#include <hebiros/AddModelFromURDFSrvRequest.h>
#include <hebiros/AddModelFromURDFSrvResponse.h>


namespace hebiros
{

struct AddModelFromURDFSrv
{

typedef AddModelFromURDFSrvRequest Request;
typedef AddModelFromURDFSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddModelFromURDFSrv
} // namespace hebiros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hebiros::AddModelFromURDFSrv > {
  static const char* value()
  {
    return "7503667ca5355c5a12e4de26d45dcf94";
  }

  static const char* value(const ::hebiros::AddModelFromURDFSrv&) { return value(); }
};

template<>
struct DataType< ::hebiros::AddModelFromURDFSrv > {
  static const char* value()
  {
    return "hebiros/AddModelFromURDFSrv";
  }

  static const char* value(const ::hebiros::AddModelFromURDFSrv&) { return value(); }
};


// service_traits::MD5Sum< ::hebiros::AddModelFromURDFSrvRequest> should match 
// service_traits::MD5Sum< ::hebiros::AddModelFromURDFSrv > 
template<>
struct MD5Sum< ::hebiros::AddModelFromURDFSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hebiros::AddModelFromURDFSrv >::value();
  }
  static const char* value(const ::hebiros::AddModelFromURDFSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebiros::AddModelFromURDFSrvRequest> should match 
// service_traits::DataType< ::hebiros::AddModelFromURDFSrv > 
template<>
struct DataType< ::hebiros::AddModelFromURDFSrvRequest>
{
  static const char* value()
  {
    return DataType< ::hebiros::AddModelFromURDFSrv >::value();
  }
  static const char* value(const ::hebiros::AddModelFromURDFSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hebiros::AddModelFromURDFSrvResponse> should match 
// service_traits::MD5Sum< ::hebiros::AddModelFromURDFSrv > 
template<>
struct MD5Sum< ::hebiros::AddModelFromURDFSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hebiros::AddModelFromURDFSrv >::value();
  }
  static const char* value(const ::hebiros::AddModelFromURDFSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebiros::AddModelFromURDFSrvResponse> should match 
// service_traits::DataType< ::hebiros::AddModelFromURDFSrv > 
template<>
struct DataType< ::hebiros::AddModelFromURDFSrvResponse>
{
  static const char* value()
  {
    return DataType< ::hebiros::AddModelFromURDFSrv >::value();
  }
  static const char* value(const ::hebiros::AddModelFromURDFSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HEBIROS_MESSAGE_ADDMODELFROMURDFSRV_H
