// Generated by gencpp from file hebiros/ModelFkSrv.msg
// DO NOT EDIT!


#ifndef HEBIROS_MESSAGE_MODELFKSRV_H
#define HEBIROS_MESSAGE_MODELFKSRV_H

#include <ros/service_traits.h>


#include <hebiros/ModelFkSrvRequest.h>
#include <hebiros/ModelFkSrvResponse.h>


namespace hebiros
{

struct ModelFkSrv
{

typedef ModelFkSrvRequest Request;
typedef ModelFkSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ModelFkSrv
} // namespace hebiros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hebiros::ModelFkSrv > {
  static const char* value()
  {
    return "0a7e86c595699ff4b039262ca7d90490";
  }

  static const char* value(const ::hebiros::ModelFkSrv&) { return value(); }
};

template<>
struct DataType< ::hebiros::ModelFkSrv > {
  static const char* value()
  {
    return "hebiros/ModelFkSrv";
  }

  static const char* value(const ::hebiros::ModelFkSrv&) { return value(); }
};


// service_traits::MD5Sum< ::hebiros::ModelFkSrvRequest> should match 
// service_traits::MD5Sum< ::hebiros::ModelFkSrv > 
template<>
struct MD5Sum< ::hebiros::ModelFkSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hebiros::ModelFkSrv >::value();
  }
  static const char* value(const ::hebiros::ModelFkSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebiros::ModelFkSrvRequest> should match 
// service_traits::DataType< ::hebiros::ModelFkSrv > 
template<>
struct DataType< ::hebiros::ModelFkSrvRequest>
{
  static const char* value()
  {
    return DataType< ::hebiros::ModelFkSrv >::value();
  }
  static const char* value(const ::hebiros::ModelFkSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hebiros::ModelFkSrvResponse> should match 
// service_traits::MD5Sum< ::hebiros::ModelFkSrv > 
template<>
struct MD5Sum< ::hebiros::ModelFkSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hebiros::ModelFkSrv >::value();
  }
  static const char* value(const ::hebiros::ModelFkSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebiros::ModelFkSrvResponse> should match 
// service_traits::DataType< ::hebiros::ModelFkSrv > 
template<>
struct DataType< ::hebiros::ModelFkSrvResponse>
{
  static const char* value()
  {
    return DataType< ::hebiros::ModelFkSrv >::value();
  }
  static const char* value(const ::hebiros::ModelFkSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HEBIROS_MESSAGE_MODELFKSRV_H
