// Generated by gencpp from file hebiros/AddGroupFromURDFSrv.msg
// DO NOT EDIT!


#ifndef HEBIROS_MESSAGE_ADDGROUPFROMURDFSRV_H
#define HEBIROS_MESSAGE_ADDGROUPFROMURDFSRV_H

#include <ros/service_traits.h>


#include <hebiros/AddGroupFromURDFSrvRequest.h>
#include <hebiros/AddGroupFromURDFSrvResponse.h>


namespace hebiros
{

struct AddGroupFromURDFSrv
{

typedef AddGroupFromURDFSrvRequest Request;
typedef AddGroupFromURDFSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddGroupFromURDFSrv
} // namespace hebiros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hebiros::AddGroupFromURDFSrv > {
  static const char* value()
  {
    return "967d0b0c0d858ded8a6a69abbce0c981";
  }

  static const char* value(const ::hebiros::AddGroupFromURDFSrv&) { return value(); }
};

template<>
struct DataType< ::hebiros::AddGroupFromURDFSrv > {
  static const char* value()
  {
    return "hebiros/AddGroupFromURDFSrv";
  }

  static const char* value(const ::hebiros::AddGroupFromURDFSrv&) { return value(); }
};


// service_traits::MD5Sum< ::hebiros::AddGroupFromURDFSrvRequest> should match 
// service_traits::MD5Sum< ::hebiros::AddGroupFromURDFSrv > 
template<>
struct MD5Sum< ::hebiros::AddGroupFromURDFSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hebiros::AddGroupFromURDFSrv >::value();
  }
  static const char* value(const ::hebiros::AddGroupFromURDFSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebiros::AddGroupFromURDFSrvRequest> should match 
// service_traits::DataType< ::hebiros::AddGroupFromURDFSrv > 
template<>
struct DataType< ::hebiros::AddGroupFromURDFSrvRequest>
{
  static const char* value()
  {
    return DataType< ::hebiros::AddGroupFromURDFSrv >::value();
  }
  static const char* value(const ::hebiros::AddGroupFromURDFSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hebiros::AddGroupFromURDFSrvResponse> should match 
// service_traits::MD5Sum< ::hebiros::AddGroupFromURDFSrv > 
template<>
struct MD5Sum< ::hebiros::AddGroupFromURDFSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hebiros::AddGroupFromURDFSrv >::value();
  }
  static const char* value(const ::hebiros::AddGroupFromURDFSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebiros::AddGroupFromURDFSrvResponse> should match 
// service_traits::DataType< ::hebiros::AddGroupFromURDFSrv > 
template<>
struct DataType< ::hebiros::AddGroupFromURDFSrvResponse>
{
  static const char* value()
  {
    return DataType< ::hebiros::AddGroupFromURDFSrv >::value();
  }
  static const char* value(const ::hebiros::AddGroupFromURDFSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HEBIROS_MESSAGE_ADDGROUPFROMURDFSRV_H
