// Generated by gencpp from file hebiros/ModelFkSrvResponse.msg
// DO NOT EDIT!


#ifndef HEBIROS_MESSAGE_MODELFKSRVRESPONSE_H
#define HEBIROS_MESSAGE_MODELFKSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hebiros
{
template <class ContainerAllocator>
struct ModelFkSrvResponse_
{
  typedef ModelFkSrvResponse_<ContainerAllocator> Type;

  ModelFkSrvResponse_()
    : frames()  {
    }
  ModelFkSrvResponse_(const ContainerAllocator& _alloc)
    : frames(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _frames_type;
  _frames_type frames;





  typedef boost::shared_ptr< ::hebiros::ModelFkSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hebiros::ModelFkSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ModelFkSrvResponse_

typedef ::hebiros::ModelFkSrvResponse_<std::allocator<void> > ModelFkSrvResponse;

typedef boost::shared_ptr< ::hebiros::ModelFkSrvResponse > ModelFkSrvResponsePtr;
typedef boost::shared_ptr< ::hebiros::ModelFkSrvResponse const> ModelFkSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hebiros::ModelFkSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hebiros::ModelFkSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hebiros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'hebiros': ['/home/robot/catkin_ws/src/hebiros/hebiros/msg', '/home/robot/catkin_ws/devel/share/hebiros/msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hebiros::ModelFkSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hebiros::ModelFkSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebiros::ModelFkSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebiros::ModelFkSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebiros::ModelFkSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebiros::ModelFkSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hebiros::ModelFkSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2dbcb8d5fc4b1d0fa7d1af4a1a7dc9b";
  }

  static const char* value(const ::hebiros::ModelFkSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2dbcb8d5fc4b1d0ULL;
  static const uint64_t static_value2 = 0xfa7d1af4a1a7dc9bULL;
};

template<class ContainerAllocator>
struct DataType< ::hebiros::ModelFkSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hebiros/ModelFkSrvResponse";
  }

  static const char* value(const ::hebiros::ModelFkSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hebiros::ModelFkSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] frames\n"
"\n"
"\n"
;
  }

  static const char* value(const ::hebiros::ModelFkSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hebiros::ModelFkSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frames);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModelFkSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hebiros::ModelFkSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hebiros::ModelFkSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "frames[]" << std::endl;
    for (size_t i = 0; i < v.frames.size(); ++i)
    {
      s << indent << "  frames[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.frames[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEBIROS_MESSAGE_MODELFKSRVRESPONSE_H
